### ISSUE TITLE
Finish Command line.

### ISSUE THREAD

**Issue by AraHaan** [IzunaDevs/nsfw_dl#3]
Currently the Command line was started, but is not complete in ``__main__.py``. This needs to be completed.

I am thinking with an command line prefix similar to pip's. Not sure on what to use to process the options. I guess there are a few modules that can probably do the same exact thing. 🤔

Also on top of that I know there must be an ``--download`` option that can download the response to an file. Not sure about some sort of auto file name based upon the file names on the url's (like maybe basename the urls to extract the file name from the url?).

**Comment by AraHaan** [comment]
I think we also need to setup an CI (like Travis or something) And to well, figure out an code coverage where it highlights lines of code covered by tests in green. Overall I think it should help. Maybe an code coverage similar to what aiohttp has?

**Comment by AraHaan** [comment]
Looks like we still need the command line and documentations for this.

**Comment by Martmists-GH** [comment]
TODO:
Test and fix bugs if needed

**Comment by AraHaan** [comment]
I cant seem to get the command line working at all. I think having all the sources be an indivitual switch might be an better option?

**Comment by Martmists-GH** [comment]
use `python setup.py install` and then `nsfw_dl` or `python -m nsfw_dl`

**Comment by AraHaan** [comment]
I think this is done now. However I wish the ``-d`` and the ``--download`` option presence would automatically set the download value to true and false otherwise.
