### ISSUE TITLE
Break Package functionality on new releases.

### ISSUE THREAD

**Issue by AraHaan** [IzunaDevs/nsfw_dl#5]
So, I am thinking to further discourage older more unsupported versions of this package, I think we should code in a special exception when it checks and finds a newer version on pypi of itself. This is to ensure and tell the user to install the latest release that can get support with this repo.

This will Also help eliminate issues people open on here that have already been fixed and addressed on the latest release.

**Comment by Martmists-GH** [comment]
This is bad design and should not be encouraged.

**Comment by AraHaan** [comment]
alright.
